const students = [
    {"codigo":"12301",
    "nombres":"BEATRIZ",
    "apellidos":"PINZON",
    "edad":"23",
    "mat1":"Economia",
    "mat2":"Contabilidad",
    "mat3": "Finanzas",
    "cal1": 45,
    "cal2": 50,
    "cal3": 49, 
    "foto":"https://cloudfront-us-east-1.images.arcpublishing.com/infobae/5TRUDDVJ7FDY7CSSKX75KU5W4A.png",
    },

    {"codigo":"12302",
    "nombres":"ARMANDO",
    "apellidos":"MENDOZA",
    "edad":"27",
    "mat1":"Calculo",
    "mat2":"Contabilidad",
    "mat3": "Finanzas",
    "cal1": 35,
    "cal2": 37,
    "cal3": 40, 
    "foto":"https://www.terra.cl/u/fotografias/m/2021/7/18/f638x638-13377_71544_3539.png",
    },

    {"codigo":"12303",
    "nombres":"PATRICIA",
    "apellidos":"FERNANDEZ",
    "edad":"22",
    "mat1":"Comunicacion",
    "mat2":"Diseño",
    "mat3": "Modas",
    "cal1": 45,
    "cal2": 42,
    "cal3": 39, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsKTX1TSnregxn1IktZAWiNXIiJQLlprGBQQ&usqp=CAU",
    },

    {"codigo":"12304",
    "nombres":"MARCELA",
    "apellidos":"VALENCIA",
    "edad":"25",
    "mat1":"Belleza",
    "mat2":"Contabilidad",
    "mat3": "Modas",
    "cal1": 40,
    "cal2": 39,
    "cal3": 45, 
    "foto":"https://www.metroworldnews.com/resizer/lP6kjXsichLwBxX_WHQxPvcyWK0=/800x0/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/YVPLSKV3QBCMVGVSG6RPUNHTF4.JPG",
    },

    {"codigo":"12305",
    "nombres":"DANIEL",
    "apellidos":"VALENCIA",
    "edad":"30",
    "mat1":"Finanzas",
    "mat2":"Contabilidad",
    "mat3": "Comunicacion",
    "cal1": 40,
    "cal2": 39,
    "cal3": 44, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvwagrFe5fjyoPQBvjRi4wNpJF1koTy75KKOqHvEw-dGXjXaKLdibFjOjOxgzrFswYiFc&usqp=CAU",
    },

    {"codigo":"12306",
    "nombres":"AURA MARIA",
    "apellidos":"FUENTES",
    "edad":"26",
    "mat1":"Artes",
    "mat2":"Comunicacion",
    "mat3": "Humanidades",
    "cal1": 37,
    "cal2": 42,
    "cal3": 40, 
    "foto":"https://www.terra.cl/u/fotografias/m/2021/3/22/f768x1-8993_9120_5050.jpg",
    },
    
    {"codigo":"12307",
    "nombres":"INES",
    "apellidos":"RAMIREZ",
    "edad":"55",
    "mat1":"Artes",
    "mat2":"Diseño",
    "mat3": "Modas",
    "cal1": 44,
    "cal2": 46,
    "cal3": 40, 
    "foto":"https://www.infobae.com/new-resizer/xi-dd3Fqy9rzYBFNFq0FpzH3x-0=/1200x900/filters:format(webp):quality(85)//cloudfront-us-east-1.images.arcpublishing.com/infobae/KR34VXFXANF65BUBX66M2I3FFE.png",
    },

    {"codigo":"12308",
    "nombres":"MARIANA",
    "apellidos":"VALDEZ",
    "edad":"26",
    "mat1":"Religion",
    "mat2":"Belleza",
    "mat3": "Modas",
    "cal1": 39,
    "cal2": 40,
    "cal3": 42, 
    "foto":"https://trome.com/resizer/mEVTLPBhnUiXjUMePQ92d4MHB_A=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Q2PSW6OEEREYFNNCXHIGPAVWCA.jpg",
    },

    {"codigo":"12309",
    "nombres":"SOFIA",
    "apellidos":"DE RODRIGUEZ",
    "edad":"38",
    "mat1":"Belleza",
    "mat2":"Contabilidad",
    "mat3": "Economia",
    "cal1": 38,
    "cal2": 40,
    "cal3": 30,
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8zrS1q63dXmOamyXWPR95sHJNZUZwls57Sg&usqp=CAU",
    },

    {"codigo":"12310",
    "nombres":"BERTHA",
    "apellidos":"DE GONZALES",
    "edad":"37",
    "mat1":"Artes",
    "mat2":"Diseño",
    "mat3": "Comunicacion",
    "cal1": 44,
    "cal2": 39,
    "cal3": 42, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9X0loc560CRlbRlbptAkhzeyN4DdX_PhuFw&usqp=CAU",
    },

    {"codigo":"12311",
    "nombres":"HUGO",
    "apellidos":"LOMBARDI",
    "edad":"40",
    "mat1":"Modas",
    "mat2":"Diseño",
    "mat3": "Artes",
    "cal1": 45,
    "cal2": 47,
    "cal3": 48, 
    "foto":"http://imagenes.canalrcn.com/imgYoSoyBettyLaFea/hugo.jpg",
    },

    {"codigo":"12312",
    "nombres":"SAUL",
    "apellidos":"GUTIERREZ",
    "edad":"48",
    "mat1":"Comunicacion",
    "mat2":"Humanidades",
    "mat3": "Religion",
    "cal1": 45,
    "cal2": 50,
    "cal3": 49, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEd1C1go4rKh3C393jppcITEpUgAFv-l9avIgzaMCzCAzKkIyJVKCVCXlGdLWEHgGV7wA&usqp=CAU",
    },

    {"codigo":"12313",
    "nombres":"FREDDY",
    "apellidos":"CONTRERAS",
    "edad":"25",
    "mat1":"Comunicacion",
    "mat2":"Humanidades",
    "mat3": "Religion",
    "cal1": 45,
    "cal2": 50,
    "cal3": 49, 
    "foto":"https://depor.com/resizer/GYz5iv3lAhpxBTqafYeXQ_AWZaU=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/ICYYYQTIOBDYHDEVU2PSFV67IQ.JPG",
    },

    {"codigo":"12314",
    "nombres":"WILSON",
    "apellidos":"SASTOQUE",
    "edad":"30",
    "mat1":"Comunicacion",
    "mat2":"Religion",
    "mat3": "Humanidades",
    "cal1": 45,
    "cal2": 50,
    "cal3": 49, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7Djs6taLeWbR-6oXn1Xhg_CDNSOwTn0meAdHKkSCdwYD_CjgpOnhVwQb8JxVNi1DTzw4&usqp=CAU",
    },

    {"codigo":"12315",
    "nombres":"SANDRA",
    "apellidos":"PATIÑO",
    "edad":"28",
    "mat1":"Humanidades",
    "mat2":"Diseño",
    "mat3": "Modas",
    "cal1": 32,
    "cal2": 37,
    "cal3": 39, 
    "foto":"https://cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/UTYRZ6E3KJHSPJF7RADLXRK7Y4.jpg",
    },

    {"codigo":"12316",
    "nombres":"MARIO",
    "apellidos":"CALDERON",
    "edad":"27",
    "mat1":"Economia",
    "mat2":"Contabilidad",
    "mat3": "Finanzas",
    "cal1": 35,
    "cal2": 33,
    "cal3": 32, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXR8WG-Sh8o4AewEzB4jZ62ROLsQVNlnJgWQ&usqp=CAU",
    },

    {"codigo":"12317",
    "nombres":"NICOLAS",
    "apellidos":"MORA",
    "edad":"24",
    "mat1":"Finanzas",
    "mat2":"Contabilidad",
    "mat3": "Economia",
    "cal1": 47,
    "cal2": 50,
    "cal3": 47,
    "foto":"http://imagenes.canalrcn.com/imgYoSoyBettyLaFea/nicolas.jpg",
    },

    {"codigo":"12318",
    "nombres":"GUSTAVO",
    "apellidos":"OLARTEZ",
    "edad":"42",
    "mat1":"Humanidades",
    "mat2":"Contabilidad",
    "mat3": "Comunicacion",
    "cal1": 40,
    "cal2": 42,
    "cal3": 39, 
    "foto":"https://cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/DEACELNRN5H6BEV7C5LWKLS6ME.JPG",
    },

    {"codigo":"12319",
    "nombres":"CATALINA",
    "apellidos":"ANGEL",
    "edad":"38",
    "mat1":"Modas",
    "mat2":"Belleza",
    "mat3":"Comunicacion",
    "cal1": 40,
    "cal2": 37,
    "cal3": 44, 
    "foto":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeN4HPumqeWV52aHBYaP5cQq517oy-hdnnhA&usqp=CAU",
    },

    {"codigo":"12320",
    "nombres":"MICHEL",
    "apellidos":"DOINEL",
    "edad":"32",
    "mat1":"Modas",
    "mat2":"Belleza",
    "mat3": "Artes",
    "cal1": 45,
    "cal2": 45,
    "cal3": 40, 
    "foto":"https://www.mdzol.com/u/fotografias/m/2020/12/31/f1280x720-1000714_1132389_5236.jpg",
    },
]
